# -*- coding: utf-8 -*-
"""Tarapur-AI-Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KASgwFu5aQNSdbF3Kd1bn-FnKgViYPYu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# ==========================================
# 1. DATASET PREPARATION (Tarapur Case Study)
# ==========================================
# Creating a synthetic dataset based on Tarapur industrial patterns
data = {
    'pH': [7.2, 8.5, 6.1, 4.5, 9.2, 7.0, 5.2, 8.1, 6.8, 7.5],
    'BOD': [20, 150, 45, 300, 25, 10, 500, 15, 200, 25],
    'COD': [100, 600, 150, 900, 120, 50, 1500, 80, 500, 90],
    'TSS': [30, 150, 60, 400, 40, 20, 600, 25, 250, 35],
    'TDS': [500, 2500, 1200, 5000, 800, 400, 7000, 600, 3000, 700],
    'Target': [0, 1, 1, 1, 1, 0, 1, 0, 1, 0] # 0 = Safe, 1 = Critical
}

df = pd.DataFrame(data)

# Feature Engineering: Adding the Biodegradability Index (Environmental Science Key)
df['BI_Ratio'] = df['BOD'] / df['COD']

# ==========================================
# 2. MODEL TRAINING
# ==========================================
X = df.drop('Target', axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# ==========================================
# 3. VISUALIZATION: FEATURE IMPORTANCE
# ==========================================
def plot_importance():
    feature_importance = pd.Series(model.feature_importances_, index=X.columns)
    plt.figure(figsize=(10, 5))
    sns.barplot(x=feature_importance, y=feature_importance.index, palette='viridis')
    plt.title("Tarapur Case Study: Which Pollutant is the Best Predictor of Violation?")
    plt.xlabel("Importance Score")
    plt.show()

plot_importance()

# ==========================================
# 4. THE SMART ALERT SYSTEM
# ==========================================
# CPCB Standards for Discharge
LIMITS = {
    "pH_min": 5.5, "pH_max": 9.0,
    "BOD": 30.0, "COD": 250.0,
    "TSS": 100.0, "TDS": 2100.0
}

def check_effluent_safety(ph, bod, cod, tss, tds):
    violations = []

    # Check Regulatory Compliance
    if not (LIMITS["pH_min"] <= ph <= LIMITS["pH_max"]):
        violations.append(f"pH ({ph}) outside range 5.5-9.0")
    if bod > LIMITS["BOD"]:
        violations.append(f"BOD ({bod} mg/L) exceeds limit of 30")
    if cod > LIMITS["COD"]:
        violations.append(f"COD ({cod} mg/L) exceeds limit of 250")
    if tss > LIMITS["TSS"]:
        violations.append(f"TSS ({tss} mg/L) exceeds limit of 100")
    if tds > LIMITS["TDS"]:
        violations.append(f"TDS ({tds} mg/L) exceeds limit of 2100")

    # Calculate BI Ratio for Environmental Depth
    bi_ratio = bod / cod if cod > 0 else 0

    # Print Report
    print("\n" + "="*45)
    print("      AI MONITORING SYSTEM: TARAPUR CLUSTER")
    print("="*45)

    if not violations:
        print("✅ STATUS: COMPLIANT (SAFE)")
        print("All parameters are within MPCB/CPCB norms.")
    else:
        print("🚨 ALERT: CRITICAL VIOLATION DETECTED")
        for v in violations:
            print(f" -> {v}")

    if bi_ratio < 0.3 and cod > 0:
        print("\n⚠️ TOXICITY WARNING:")
        print(f"Biodegradability Index is low ({bi_ratio:.2f}).")
        print("Possible non-biodegradable Pharma/Chemical waste detected.")

    print("="*45)

# ==========================================
# 5. INTERACTIVE PANEL (COLAB FORMS)
# ==========================================
#@title 🔍 Enter Sensor Readings for Real-Time Alert
pH_Level = 6.1 #@param {type:"slider", min:0, max:14, step:0.1}
BOD_mgL = 20 #@param {type:"number"}
COD_mgL = 200 #@param {type:"number"}
TSS_mgL = 45 #@param {type:"number"}
TDS_mgL = 1500 #@param {type:"number"}

# Run the alert check
check_effluent_safety(pH_Level, BOD_mgL, COD_mgL, TSS_mgL, TDS_mgL)